// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using openMob.Core.Data;

#nullable enable

namespace openMob.Core.Data.Migrations;

[DbContext(typeof(AppDbContext))]
partial class AppDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

        modelBuilder.Entity("openMob.Core.Data.Entities.ServerConnection", b =>
        {
            b.Property<string>("Id")
                .HasColumnType("TEXT");

            b.Property<DateTimeOffset>("CreatedAt")
                .HasColumnType("TEXT");

            b.Property<bool>("DiscoveredViaMdns")
                .ValueGeneratedOnAdd()
                .HasColumnType("INTEGER")
                .HasDefaultValue(false);

            b.Property<string>("Host")
                .IsRequired()
                .HasColumnType("TEXT");

            b.Property<bool>("IsActive")
                .ValueGeneratedOnAdd()
                .HasColumnType("INTEGER")
                .HasDefaultValue(false);

            b.Property<string>("Name")
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnType("TEXT");

            b.Property<int>("Port")
                .ValueGeneratedOnAdd()
                .HasColumnType("INTEGER")
                .HasDefaultValue(4096);

            b.Property<DateTimeOffset>("UpdatedAt")
                .HasColumnType("TEXT");

            b.Property<string>("Username")
                .HasColumnType("TEXT");

            b.HasKey("Id");

            b.HasIndex("IsActive");

            b.ToTable("ServerConnections");
        });
#pragma warning restore 612, 618
    }
}
