// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace openMob.Core.Data.CompiledModels
{
    public partial class AppDbContextModel
    {
        private AppDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("8842ec0f-801c-4079-8609-efe77d621336"), entityTypeCount: 3)
        {
        }

        partial void Initialize()
        {
            var appState = AppStateEntityType.Create(this);
            var projectPreference = ProjectPreferenceEntityType.Create(this);
            var serverConnection = ServerConnectionEntityType.Create(this);

            AppStateEntityType.CreateAnnotations(appState);
            ProjectPreferenceEntityType.CreateAnnotations(projectPreference);
            ServerConnectionEntityType.CreateAnnotations(serverConnection);

            AddAnnotation("ProductVersion", "9.0.14");
        }
    }
}
