// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using openMob.Core.Data;
using openMob.Core.Data.CompiledModels;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(AppDbContext), typeof(AppDbContextModel))]
