// <auto-generated />
using System;
using System.Reflection;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using openMob.Core.Data.Entities;
using openMob.Core.Models;

#pragma warning disable 219, 612, 618
#nullable disable

namespace openMob.Core.Data.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class ProjectPreferenceEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "openMob.Core.Data.Entities.ProjectPreference",
                typeof(ProjectPreference),
                baseEntityType,
                propertyCount: 5,
                keyCount: 1);

            var projectId = runtimeEntityType.AddProperty(
                "ProjectId",
                typeof(string),
                propertyInfo: typeof(ProjectPreference).GetProperty("ProjectId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ProjectPreference).GetField("<ProjectId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                maxLength: 500);

            var agentName = runtimeEntityType.AddProperty(
                "AgentName",
                typeof(string),
                propertyInfo: typeof(ProjectPreference).GetProperty("AgentName", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ProjectPreference).GetField("<AgentName>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 500);

            var autoAccept = runtimeEntityType.AddProperty(
                "AutoAccept",
                typeof(bool),
                propertyInfo: typeof(ProjectPreference).GetProperty("AutoAccept", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ProjectPreference).GetField("<AutoAccept>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                sentinel: false);
            autoAccept.AddAnnotation("Relational:DefaultValue", false);

            var defaultModelId = runtimeEntityType.AddProperty(
                "DefaultModelId",
                typeof(string),
                propertyInfo: typeof(ProjectPreference).GetProperty("DefaultModelId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ProjectPreference).GetField("<DefaultModelId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 500);

            var thinkingLevel = runtimeEntityType.AddProperty(
                "ThinkingLevel",
                typeof(ThinkingLevel),
                propertyInfo: typeof(ProjectPreference).GetProperty("ThinkingLevel", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ProjectPreference).GetField("<ThinkingLevel>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                providerPropertyType: typeof(int));
            thinkingLevel.SetSentinelFromProviderValue(0);
            thinkingLevel.AddAnnotation("Relational:DefaultValue", ThinkingLevel.Medium);

            var key = runtimeEntityType.AddKey(
                new[] { projectId });
            runtimeEntityType.SetPrimaryKey(key);

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "ProjectPreferences");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
